name: 'Solar2D Plugin Updater'
description: 'Creates a release and requests directory update'
inputs:
  pat:
    description: personal access token required to automatically publish to directory
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - name: prepare
      shell: bash
      run: |
        cd plugins
        for build in *
        do
        (
          if [ ! -d "$build" ] ; then continue ; fi
          cd "$build"
          for platform in *
          do
            (
              if [ ! -d "$platform" ] ; then continue ; fi
              cd "$platform"
              if ! ls * &> /dev/null  ; then continue ; fi
              COPYFILE_DISABLE=true tar -czvf ../../"$build-$platform.tgz" --exclude=".*" *
            )
          done
        )
        done
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: plugins/*.tgz
        name: Release v${{ github.run_number }}
        tag_name: v${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Directory update request
      shell: bash
      run: |
        [ -z "${{ inputs.pat }}" ] && echo "Skipping, no ISSUE_PAT" && exit 0
        curl --request POST \
        --url https://api.github.com/repos/solar2d/plugins.solar2d.com/dispatches \
        --header 'authorization: Bearer ${{ inputs.pat }}' \
        --header 'content-type: application/json' \
        --data '{
          "event_type": "repo_updated",
          "client_payload": {
              "repo": "${{ github.repository }}"
            }
          }'